package transcript

import "testing"

func TestParseHidesInjectedUserText(t *testing.T) {
	data := []byte(`{"type":"user","message":{"role":"user","content":"<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>"}}
{"type":"user","message":{"role":"user","content":"<local-command-stdout>Login successful</local-command-stdout>"}}
{"type":"user","message":{"role":"user","content":[{"type":"text","text":"<system-reminder>ctx</system-reminder>"},{"type":"text","text":"real question"}]}}
{"type":"user","message":{"role":"user","content":"<command-name>/login</command-name>"}}
`)
	msgs := ParseBytes(data)
	if len(msgs) != 1 || msgs[0].Kind != KindUser || msgs[0].Text != "real question" {
		t.Fatalf("got %+v, want only the real question", msgs)
	}
}
