package hookcfg

// The status line relay. Claude Code runs settings.json's statusLine command
// on every UI update with the session's status JSON (model, cost, context
// window, lines changed …) on stdin. ccdash puts a relay there that POSTs
// that JSON to the collector in the background — the portal draws its own
// status line from it — and then runs the operator's original statusLine
// command with the same input, so the terminal looks exactly as before.
// The original setting is kept in StatusLineOrigPath for uninstall.

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/takumanakagame/ccmanage/internal/paths"
)

// StatusLineEndpoint receives the relayed status JSON.
const StatusLineEndpoint = "/hooks/statusline"

// statusLineMarker identifies our relay in settings.json's statusLine.
const statusLineMarker = "ccdash/statusline.sh"

func isManagedStatusLine(v any) bool {
	m, _ := v.(map[string]any)
	cmd, _ := m["command"].(string)
	return strings.Contains(cmd, statusLineMarker)
}

// wrapStatusLine points settings' statusLine at the relay. It returns the
// operator's original statusLine (nil when there was none) and its command,
// read back from origPath when the relay is already installed.
func wrapStatusLine(settings map[string]any, scriptPath, origPath string) (orig any, origCmd string) {
	cur := settings["statusLine"]
	if isManagedStatusLine(cur) {
		orig = readOrigStatusLine(origPath)
	} else {
		orig = cur
	}
	next := map[string]any{}
	if m, ok := orig.(map[string]any); ok {
		for k, v := range m { // keep padding etc.
			next[k] = v
		}
		if m["type"] == "command" || m["type"] == nil {
			origCmd, _ = m["command"].(string)
		}
	}
	next["type"] = "command"
	next["command"] = shellQuote(scriptPath)
	settings["statusLine"] = next
	return orig, origCmd
}

// unwrapStatusLine restores the original statusLine (or removes ours when
// there was none). No-op unless the relay is installed.
func unwrapStatusLine(settings map[string]any, origPath string) bool {
	if !isManagedStatusLine(settings["statusLine"]) {
		return false
	}
	if orig := readOrigStatusLine(origPath); orig != nil {
		settings["statusLine"] = orig
	} else {
		delete(settings, "statusLine")
	}
	return true
}

func readOrigStatusLine(origPath string) any {
	b, err := os.ReadFile(origPath)
	if err != nil {
		return nil
	}
	var w struct {
		StatusLine any `json:"statusLine"`
	}
	if json.Unmarshal(b, &w) != nil {
		return nil
	}
	return w.StatusLine
}

// persistStatusLine writes the original setting and the relay script.
func persistStatusLine(orig any, origCmd, scriptPath, origPath, tokenPath, baseURL string) error {
	if err := os.MkdirAll(filepath.Dir(scriptPath), 0o700); err != nil {
		return err
	}
	b, _ := json.MarshalIndent(map[string]any{"statusLine": orig}, "", "  ")
	if err := os.WriteFile(origPath, b, 0o600); err != nil {
		return err
	}
	body := fmt.Sprintf(statusLineScriptTemplate, baseURL, tokenPath, shellQuote(origCmd))
	tmp := scriptPath + ".tmp"
	if err := os.WriteFile(tmp, []byte(body), 0o700); err != nil {
		return err
	}
	return os.Rename(tmp, scriptPath)
}

// statusLineScriptTemplate: %[1]s collector base URL, %[2]s token file,
// %[3]s the original command, shell-quoted ('' when none).
const statusLineScriptTemplate = `#!/bin/sh
# ccdash status line relay — generated by ` + "`ccdash install-hooks`" + `.
# DO NOT EDIT: rewritten on every install. Your own statusLine command is
# kept below (and in statusline.orig.json); uninstall-hooks puts it back.
#
# Forwards Claude Code's status JSON to the collector in the background
# (never blocks: a stopped ccdash costs nothing), then runs the original
# command with the same input so the terminal shows what it always did.
set -u
input="$(cat)"

tok="$(cat "%[2]s" 2>/dev/null || true)"
tok="$(printf '%%s' "$tok" | tr -d '[:space:]')"
if [ -n "$tok" ]; then
  (
    printf '%%s' "$input" | curl -sS --max-time 2 -X POST "%[1]s` + StatusLineEndpoint + `" \
      -H "X-Ccdash-Token: $tok" \
      -H "X-Ccdash-Managed: true" \
      -H "Content-Type: application/json" \
      --data-binary @- \
  ) </dev/null >/dev/null 2>&1 &
fi

orig=%[3]s
[ -n "$orig" ] || exit 0
printf '%%s' "$input" | sh -c "$orig"
`

// InstallStatusLine installs only the status line relay (for setups that
// don't use ccdash's hooks).
func (in *Install) InstallStatusLine() error {
	settings, err := readSettings(in.Path)
	if err != nil {
		return err
	}
	if err := in.applyStatusLine(settings); err != nil {
		return err
	}
	if in.DryRun {
		buf, _ := json.MarshalIndent(settings, "", "  ")
		fmt.Println(string(buf))
		return nil
	}
	return writeSettings(in.Path, settings)
}

// RemoveStatusLine restores the original statusLine.
func (in *Install) RemoveStatusLine() error {
	settings, err := readSettings(in.Path)
	if err != nil {
		return err
	}
	origPath, err := paths.StatusLineOrigPath()
	if err != nil {
		return err
	}
	if !unwrapStatusLine(settings, origPath) {
		return nil
	}
	if err := writeSettings(in.Path, settings); err != nil {
		return err
	}
	removeStatusLineFiles()
	return nil
}

// applyStatusLine wraps settings' statusLine and (unless DryRun) writes the
// relay and the saved original — before settings.json, so it never points
// at a missing script.
func (in *Install) applyStatusLine(settings map[string]any) error {
	scriptPath, err := paths.StatusLineScriptPath()
	if err != nil {
		return err
	}
	origPath, err := paths.StatusLineOrigPath()
	if err != nil {
		return err
	}
	tokenPath, err := paths.TokenPath()
	if err != nil {
		return err
	}
	orig, origCmd := wrapStatusLine(settings, scriptPath, origPath)
	if in.DryRun {
		return nil
	}
	return persistStatusLine(orig, origCmd, scriptPath, origPath, tokenPath, in.BaseURL)
}

func removeStatusLineFiles() {
	for _, f := range []func() (string, error){paths.StatusLineScriptPath, paths.StatusLineOrigPath} {
		if p, err := f(); err == nil {
			_ = os.Remove(p)
		}
	}
}
